rtt: rtt_client.c rtt_server.c util.o
	gcc -o rtt_client rtt_client.c util.o
	gcc -o rtt_server rtt_server.c util.o

	

band: band_client.c band_server.c util.o
	gcc -o band_client band_client.c util.o
	gcc -o band_server band_server.c util.o

conn: conn_client.c conn_server.c util.o
	gcc -o conn_client conn_client.c util.o
	gcc -o conn_server conn_server.c util.o
	

