cache: cache.c util.o
	gcc -o cache cache.c util.o

read: rand_read.c util.o
	gcc -o rand_read rand_read.c util.o

seq: seq_read.c util.o
	gcc -o seq_read seq_read.c util.o
cont: contention.c util.o
	gcc -o cont contention.c util.o
